import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from 'react';
export default function LandingPage() {
    const [email, setEmail] = useState('');
    const handleSubmit = (e) => {
        e.preventDefault();
        alert(`Thank you! We'll notify you at ${email}`);
        setEmail('');
    };
    return (_jsxs("div", { className: "min-h-screen bg-gray-900 text-white flex flex-col items-center px-4 py-10 space-y-10", children: [_jsxs("section", { className: "text-center max-w-2xl", children: [_jsx("h1", { className: "text-4xl font-bold mb-4", children: "Smarter Chess Analysis" }), _jsx("p", { className: "text-lg text-gray-300", children: "Reflect on your games, surface critical moments, and get personalized feedback powered by Stockfish + GPT." }), _jsxs("form", { onSubmit: handleSubmit, className: "mt-6 flex flex-col sm:flex-row items-center gap-2", children: [_jsx("input", { type: "email", placeholder: "Enter your email", value: email, onChange: (e) => setEmail(e.target.value), required: true, className: "px-4 py-2 rounded text-black w-full sm:w-auto" }), _jsx("button", { type: "submit", className: "bg-blue-600 px-4 py-2 rounded hover:bg-blue-700 transition", children: "Join Early Access" })] })] }), _jsxs("section", { className: "max-w-4xl text-center", children: [_jsx("h2", { className: "text-2xl font-semibold mb-4", children: "How It Works" }), _jsxs("div", { className: "grid sm:grid-cols-3 gap-6", children: [_jsxs("div", { children: [_jsx("h3", { className: "font-bold text-lg", children: "1. Import Your Game" }), _jsx("p", { className: "text-gray-400", children: "Upload a PGN or paste from Lichess/Chess.com" })] }), _jsxs("div", { children: [_jsx("h3", { className: "font-bold text-lg", children: "2. Annotate Key Moves" }), _jsx("p", { className: "text-gray-400", children: "Capture your thought process before the engine speaks" })] }), _jsxs("div", { children: [_jsx("h3", { className: "font-bold text-lg", children: "3. Get Feedback" }), _jsx("p", { className: "text-gray-400", children: "AI-enhanced insights tailored to your annotations" })] })] })] }), _jsxs("section", { className: "max-w-4xl text-center", children: [_jsx("h2", { className: "text-2xl font-semibold mb-4", children: "Why This Tool?" }), _jsxs("ul", { className: "grid sm:grid-cols-2 gap-4 text-left", children: [_jsx("li", { children: "\u2705 Combines LLMs with Stockfish for layered analysis" }), _jsx("li", { children: "\u2705 Encourages reflection before revealing evaluations" }), _jsx("li", { children: "\u2705 Supports self-tagging of critical moments" }), _jsx("li", { children: "\u2705 Lets you analyze variations and discover patterns" })] })] }), _jsxs("section", { className: "max-w-2xl text-center", children: [_jsx("h2", { className: "text-2xl font-semibold mb-4", children: "Who It's For" }), _jsx("p", { className: "text-gray-300", children: "Tournament players, coaches, and thoughtful improvers who want more than just a +0.3." })] }), _jsx("footer", { className: "mt-10 text-gray-500 text-sm", children: "Built by a chess player \u2022 GitHub \u2022 Contact" })] }));
}
